### ISSUE TITLE
Experiments screen doesn't disappear after clicking save

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-frontend#10]
A user tried to make a new experiment, but when he clicked `save` the experiments list screen did not disappear, and the new experiment also didn't appear in the list of experiments.

**Comment by gandreadis** [comment]
With the move to a new framework (and the experiments page having been totally rewritten), this bug has become obsolete (for now). Don't hesitate to file it again though if you encounter it with the new version :)
