### ISSUE TITLE
Collaborators button on `/simulations` appears unresponsive

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-frontend#20]
Reproduction:

1. Log in
2. Press the green collaborators button
3. Nothing happens

Extra information:

In verbose mode, Chrome console says `[Violation] 'click' handler took 235ms` after a click.

**Comment by gandreadis** [comment]
For now, this is the correct behavior for that button. If you hover over it, you can see that it says that this feature is disabled for now - we don't have an implemented version of collaboration in the web stack at the moment, so we decided to turn it off for now.

The message you're seeing is something a lot of webapps are seeing lately, but I didn't find a way to disable/resolve them. For now, it's fine to ignore them

**Comment by gandreadis** [comment]
Do you think the UI communicates this sufficiently to the user for now, or should I add something?

**Comment by fabianishere** [comment]
Bootstrap has specific styles for disabled buttons. Would it be an idea to add the `.disabled` class to the button?

**Comment by gandreadis** [comment]
Great idea! I'll add that.

**Comment by gandreadis** [comment]
Done in [6acc3ce](https://github.com/atlarge-research/opendc-frontend/commit/6acc3cea080f0920d62b5b7caf9667bc8a7c536e).
