### ISSUE TITLE
Experiments page shows "no experiments" message while loading experiments

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-frontend#46]
To reproduce:
1. Open an existing simulation (that has experiments) on OpenDC
1. Switch to the Experiments tab
1. Note that there is a message "No experiments here yet... Add some with the button below!" that stays up until the experiments are loaded.

Suggested fix:
1. Show a "Loading experiments..." message while loading instead.

**Comment by gandreadis** [comment]
@leonoverweel I've implemented this, let me know if this is indeed what you had in mind :) (not yet deployed live online, but you can look at the code or run it locally)

**Comment by leonoverweel** [comment]
It's hard to see because it loads so fast locally, but it looks like it still says something along the lines of "there's nothing here yet." Is that right?

**Comment by gandreadis** [comment]
No, it should be displaying something like 'Loading Experiments...', see this file here on GitHub: https://github.com/atlarge-research/opendc-frontend/blob/master/src/components/experiments/ExperimentListComponent.js

**Comment by leonoverweel** [comment]
Hmm, maybe I did this wrong.

```bash
git clone --recursive [opendc repo]
cd opendc/opendc-frontend
git checkout master
git pull
docker-compose build
docker-compose up
```

Should I be pulling from a different branch? Clearing docker caches?

**Comment by gandreadis** [comment]
The setup looks good, could you check whether in your local version of the experiments file I linked earlier you also have the same code as is on GitHub?

**Comment by leonoverweel** [comment]
Yes, the file has the following snippet:

```html
<div className="alert alert-success">
    <span className="fa fa-refresh fa-spin mr-2" />
    <strong>Loading Experiments...</strong>
</div>
```

Maybe it's a caching issue. I'll retry with `--no-cache` on the build step (had previously built before checking out `master`).

**Comment by gandreadis** [comment]
Weird. I've never experienced these kinds of caching issues, only browser-level (so Ctrl-F5). Have you Ctrl-F5'ed already?

**Comment by leonoverweel** [comment]
Looks good - I was looking at `/simulations` instead of `/simulations/simulation-id/experiments` 😅

**Comment by gandreadis** [comment]
Haha 😄
The `/simulations` one is on my todo-list, too, just that it was a bit more involved than this one, implementation-wise.
