### ISSUE TITLE
Show experiment loading progress

### ISSUE THREAD

**Issue by leonoverweel** [atlarge-research/opendc-frontend#8]
The current UI shows a spinning circle when a user is loading an experiment, so it's unclear whether the experiment is loading successfully, or how much longer it's going to take.

Since the frontend knows both an experiment's last simulated tick and how many ticks of data it's already received, it'd be nice to show some indication of this progress.

**Comment by gandreadis** [comment]
Unfortunately, due to all states being fetched in one go, this is not feasible at the moment. As soon as we have a better caching mechanism (both in the API and on the frontend), this should, however, definitely be implemented.
